# Use the official Debian base image
FROM debian

# Update package lists
RUN apt-get update

# (Optional) Install any additional packages you need
# RUN apt-get install -y <package-name>

# (Optional) Set environment variables
# ENV MY_VARIABLE=value

# (Optional) Set a default command to run when the container starts
# CMD ["<command>", "<arg1>", "<arg2>", ...]

